<a href="https://colab.research.google.com/github/sowmyab-codes/engine-failure-prediction/blob/main/aircraftfailureprediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving train_FD001.txt to train_FD001.txt

In [2]:
import pandas as pd
data = pd.read_csv("train_FD001.txt", sep=" ", header=None)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190,NaN,NaN
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,NaN,NaN
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,NaN,NaN
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,NaN,NaN
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,NaN,NaN

In [3]:
import os
os.listdir()

['.config', 'train_FD001.txt', 'sample_data']

In [4]:
data.shape

(20631, 28)

In [5]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190,NaN,NaN
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,NaN,NaN
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,NaN,NaN
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,NaN,NaN
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,NaN,NaN

Check for null values

In [6]:
data.isnull().sum()

0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26    20631
27    20631
dtype: int64

Summary statistics

In [7]:
data.describe()

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
count,20631.000000,20631.000000,20631.000000,20631.000000,20631.0,2.063100e+04,20631.000000,20631.000000,20631.000000,2.063100e+04,...,20631.000000,20631.000000,2.063100e+04,20631.000000,20631.0,20631.0,20631.000000,20631.000000,0.0,0.0
mean,51.506568,108.807862,-0.000009,0.000002,100.0,5.186700e+02,642.680934,1590.523119,1408.933782,1.462000e+01,...,8143.752722,8.442146,3.000000e-02,393.210654,2388.0,100.0,38.816271,23.289705,NaN,NaN
std,29.227633,68.880990,0.002187,0.000293,0.0,6.537152e-11,0.500053,6.131150,9.000605,3.394700e-12,...,19.076176,0.037505,1.556432e-14,1.548763,0.0,0.0,0.180746,0.108251,NaN,NaN
min,1.000000,1.000000,-0.008700,-0.000600,100.0,5.186700e+02,641.210000,1571.040000,1382.250000,1.462000e+01,...,8099.940000,8.324900,3.000000e-02,388.000000,2388.0,100.0,38.140000,22.894200,NaN,NaN
25%,26.000000,52.000000,-0.001500,-0.000200,100.0,5.186700e+02,642.325000,1586.260000,1402.360000,1.462000e+01,...,8133.245000,8.414900,3.000000e-02,392.000000,2388.0,100.0,38.700000,23.221800,NaN,NaN
50%,52.000000,104.000000,0.000000,0.000000,100.0,5.186700e+02,642.640000,1590.100000,1408.040000,1.462000e+01,...,8140.540000,8.438900,3.000000e-02,393.000000,2388.0,100.0,38.830000,23.297900,NaN,NaN
75%,77.000000,156.000000,0.001500,0.000300,100.0,5.186700e+02,643.000000,1594.380000,1414.555000,1.462000e+01,...,8148.310000,8.465600,3.000000e-02,394.000000,2388.0,100.0,38.950000,23.366800,NaN,NaN
max,100.000000,362.000000,0.008700,0.000600,100.0,5.186700e+02,644.530000,1616.910000,1441.490000,1.462000e+01,...,8293.720000,8.584800,3.000000e-02,400.000000,2388.0,100.0,39.430000,23.618400,NaN,NaN

This shows for each column:
minimum vale, max, mean,standard deviation, quartiles

This dataset models degradation of aircraft engines.
An engine does not fails suddenly. it deteroriates gradually over many cycles.

sensor captures, temp, pressure, rotational speed, flow characterstics, mechanical stress indicators.

we will compute remaining useful life

In [8]:
data.shape
data.head()
data.isnull().sum()
data.describe()

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
count,20631.000000,20631.000000,20631.000000,20631.000000,20631.0,2.063100e+04,20631.000000,20631.000000,20631.000000,2.063100e+04,...,20631.000000,20631.000000,2.063100e+04,20631.000000,20631.0,20631.0,20631.000000,20631.000000,0.0,0.0
mean,51.506568,108.807862,-0.000009,0.000002,100.0,5.186700e+02,642.680934,1590.523119,1408.933782,1.462000e+01,...,8143.752722,8.442146,3.000000e-02,393.210654,2388.0,100.0,38.816271,23.289705,NaN,NaN
std,29.227633,68.880990,0.002187,0.000293,0.0,6.537152e-11,0.500053,6.131150,9.000605,3.394700e-12,...,19.076176,0.037505,1.556432e-14,1.548763,0.0,0.0,0.180746,0.108251,NaN,NaN
min,1.000000,1.000000,-0.008700,-0.000600,100.0,5.186700e+02,641.210000,1571.040000,1382.250000,1.462000e+01,...,8099.940000,8.324900,3.000000e-02,388.000000,2388.0,100.0,38.140000,22.894200,NaN,NaN
25%,26.000000,52.000000,-0.001500,-0.000200,100.0,5.186700e+02,642.325000,1586.260000,1402.360000,1.462000e+01,...,8133.245000,8.414900,3.000000e-02,392.000000,2388.0,100.0,38.700000,23.221800,NaN,NaN
50%,52.000000,104.000000,0.000000,0.000000,100.0,5.186700e+02,642.640000,1590.100000,1408.040000,1.462000e+01,...,8140.540000,8.438900,3.000000e-02,393.000000,2388.0,100.0,38.830000,23.297900,NaN,NaN
75%,77.000000,156.000000,0.001500,0.000300,100.0,5.186700e+02,643.000000,1594.380000,1414.555000,1.462000e+01,...,8148.310000,8.465600,3.000000e-02,394.000000,2388.0,100.0,38.950000,23.366800,NaN,NaN
max,100.000000,362.000000,0.008700,0.000600,100.0,5.186700e+02,644.530000,1616.910000,1441.490000,1.462000e+01,...,8293.720000,8.584800,3.000000e-02,400.000000,2388.0,100.0,39.430000,23.618400,NaN,NaN

Create the Target variable(RUL)

name the columns

In [9]:
data.columns = ['engine_id', 'cycle'] + [f'sensor_{i}' for i in range(1, data.shape[1]-1)]

find maximum cycle per engine

In [10]:
max_cycle = data.groupby('engine_id')['cycle'].max().reset_index()
max_cycle.columns = ['engine_id', 'max_cycle']

Attach max cycle back to original data

In [11]:
data = data.merge(max_cycle, on='engine_id')

Calculate RUL

In [12]:
data['RUL'] = data['max_cycle'] - data['cycle']

Inspect the result

In [13]:
data[['engine_id', 'cycle', 'max_cycle', 'RUL']].head(20)

    engine_id  cycle  max_cycle  RUL
0           1      1        192  191
1           1      2        192  190
2           1      3        192  189
3           1      4        192  188
4           1      5        192  187
5           1      6        192  186
6           1      7        192  185
7           1      8        192  184
8           1      9        192  183
9           1     10        192  182
10          1     11        192  181
11          1     12        192  180
12          1     13        192  179
13          1     14        192  178
14          1     15        192  177
15          1     16        192  176
16          1     17        192  175
17          1     18        192  174
18          1     19        192  173
19          1     20        192  172

Create a binary target column

In [14]:
data['failure_soon'] = (data['RUL']<=30).astype(int)

verify new column

In [15]:
data[['engine_id', 'cycle', 'RUL', 'failure_soon']].head(20)

    engine_id  cycle  RUL  failure_soon
0           1      1  191             0
1           1      2  190             0
2           1      3  189             0
3           1      4  188             0
4           1      5  187             0
5           1      6  186             0
6           1      7  185             0
7           1      8  184             0
8           1      9  183             0
9           1     10  182             0
10          1     11  181             0
11          1     12  180             0
12          1     13  179             0
13          1     14  178             0
14          1     15  177             0
15          1     16  176             0
16          1     17  175             0
17          1     18  174             0
18          1     19  173             0
19          1     20  172             0

check class disribution

In [16]:
data['failure_soon'].value_counts()

failure_soon
0    17531
1     3100
Name: count, dtype: int64

select sensor columns as features

In [17]:
feature_cols = [col for col in data.columns if 'sensor_' in col]
X = data[feature_cols]

Define target variable

In [18]:
y = data['failure_soon']

In [19]:
X.shape, y.shape

((20631, 26), (20631,))

Import required tool

In [20]:
from sklearn.model_selection import train_test_split

Perform the split

Verify sizes

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2, random_state=42)

verify sizes

In [22]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16504, 26), (4127, 26), (16504,), (4127,))

Train the machine learning Model

In [23]:
from sklearn.ensemble import RandomForestClassifier

Create the model

In [24]:
model = RandomForestClassifier(n_estimators=100, random_state=42)

Train the model

In [25]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

Make predictions on Test Data

In [26]:
y_pred = model.predict(X_test)

check some predictions

In [27]:
y_pred[:20]

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Import evaluation Metrics

In [29]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

Calculate Accuracy

In [30]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9631693724254907

Confusion metrics

In [31]:
confusion_matrix(y_test, y_pred)

array([[3490,   53],
       [  99,  485]])

Detailed classification report

In [32]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      3543
           1       0.90      0.83      0.86       584

    accuracy                           0.96      4127
   macro avg       0.94      0.91      0.92      4127
weighted avg       0.96      0.96      0.96      4127

Create Api

Install required libraries

In [33]:
!pip install fastapi uvicorn nest_asyncio pyngrok

Requirement already satisfied: fastapi in /usr/local/lib/python3.12/dist-packages (0.135.1)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.12/dist-packages (0.42.0)
Requirement already satisfied: nest_asyncio in /usr/local/lib/python3.12/dist-packages (1.6.0)
Collecting pyngrok
  Downloading pyngrok-7.5.1-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.52.1)
Requirement already satisfied: pydantic>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (2.12.3)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.0.4)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn) (8.3.1)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn) (0.16.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.7.0->fastapi) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.7.0->fastapi) (2.41.4)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette>=0.46.0->fastapi) (4.12.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (3.11)
Downloading pyngrok-7.5.1-py3-none-any.whl (24 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-7.5.1

Save model again

In [34]:
import joblib
joblib.dump(model, "engine_failure_model.pkl")

['engine_failure_model.pkl']

Write API code in colab

In [63]:
from fastapi import FastAPI
import joblib
import numpy as np

print("Step 1: Imports done")

app = FastAPI()
print("Step 2: App created")
model = joblib.load("engine_failure_model.pkl")
print("Step 3: Model Loaded")

@app.get("/")
def home():
  return{"message":"Aircraft Engine Failure Prediction API"}
print("Step 4: Home endpoint added")

@app.post("/predict")
def predict(sensors: list[float]):

  data = np.array(sensors).reshape(1, -1)
  prediction = model.predict(data)[0]

  result = "Failure Soon" if prediction == 1 else "No Failure"
  return {"prediction": result}
for route in app.routes:
  print(route.path)

Step 1: Imports done
Step 2: App created
Step 3: Model Loaded
Step 4: Home endpoint added
/openapi.json
/docs
/docs/oauth2-redirect
/redoc
/
/predict

Run API Server

In [41]:
import nest_asyncio
import uvicorn
import asyncio # Import asyncio explicitly

nest_asyncio.apply()

In [ ]:
import nest_asyncio
import uvicorn
import asyncio
nest_asyncio.apply()

# Correct way to run Uvicorn server in a Colab environment with an existing event loop
# The port should match what ngrok is configured to connect to (8000)
config = uvicorn.Config(app, host="0.0.0.0", port=8000)
server = uvicorn.Server(config)

# Get the existing event loop and run the server's serve method
loop = asyncio.get_event_loop()
loop.run_until_complete(server.serve())

INFO:     Started server process [8711]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

INFO:     103.186.41.40:0 - "GET / HTTP/1.1" 200 OK
INFO:     103.186.41.40:0 - "GET /docs HTTP/1.1" 200 OK
INFO:     103.186.41.40:0 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     103.186.41.40:0 - "POST /predict HTTP/1.1" 200 OK

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [65]:
from pyngrok import ngrok
ngrok.set_auth_token("3BaX6ecL1cbaI3kdbfSVZ3bLjNs_Yb71rWmj2qBF4vtwQ1nt")

In [66]:
from pyngrok import ngrok
public_url = ngrok.connect(8000)
print(public_url)

NgrokTunnel: "https://liminal-calamitoid-lucas.ngrok-free.dev" -> "http://localhost:8000"

In [ ]:
for route in app.routes:
  print(route.path)

In [58]:
print(len(X.columns))

26